# Generated by Django 4.2.4 on 2023-09-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance',
            field=models.IntegerField(max_length=5),
        ),
    ]
