# Generated by Django 4.2.4 on 2023-09-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_alter_distance_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Distance',
        ),
    ]
