# Generated by Django 4.2.4 on 2023-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_lookup_delete_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
