# Generated by Django 4.2.4 on 2023-11-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_alter_lookup_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lookup',
            name='value',
            field=models.DecimalField(decimal_places=8, max_digits=16),
        ),
    ]
