# Generated by Django 4.2.4 on 2023-08-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Question')),
                ('op1', models.CharField(max_length=200, verbose_name='Option 1')),
                ('op2', models.CharField(max_length=200, verbose_name='Option 2')),
                ('op3', models.CharField(max_length=200, verbose_name='Option 3')),
                ('op4', models.CharField(max_length=200, verbose_name='Option 4')),
                ('ans1', models.CharField(max_length=200, verbose_name='Answer')),
            ],
            options={
                'db_table': 'questionbank',
            },
        ),
    ]
