# Generated by Django 4.2.4 on 2023-08-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='questionbank',
            table='question',
        ),
    ]
