# Generated by Django 4.2.4 on 2023-08-21 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_alter_questionbank_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionbank',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelTable(
            name='questionbank',
            table='questionbank',
        ),
    ]
