# Generated by Django 4.2.4 on 2023-08-23 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0007_rename_question_choice_question_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='next_ques_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_question', to='questionbank.question'),
        ),
    ]
