# Generated by Django 4.2.4 on 2023-08-08 08:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(default=None, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default=datetime.date(1950, 1, 1), max_length=1, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='IsAdmin'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, default='9896456387', max_length=15, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
